#v7.1

from Loader import Config, loader   # noqa: F401
Settings = loader.settings

CONFIG_PANEL_PARAMS = [
    dict(name="Time Lapse",              attr="TIME_LAPSE",
         type="float", min=0.0, max=30.0, step=0.5,    unit="×"),
    dict(name="Time Dilation (camera)",  attr="ENABLE_TIME_DILATION_CAMERA",  type="bool"),
    dict(name="Time Dilation (objects)", attr="ENABLE_TIME_DILATION_OBJECTS", type="bool"),
    dict(name="BH Gravity",              attr="BH_GRAVITY_ON",   type="bool"),
    dict(name="BH Mergers",              attr="BH_MERGERS_ON",   type="bool"),
    dict(name="Hawking Evaporation",     attr="ENERGY_LOST",     type="bool"),
    dict(name="Hawking Evap Rate",       attr="HAWKING_EVAPORATION_RATE",
         type="float", min=0.0, max=0.01, step=0.0001, unit="M/s²"),
    dict(name="Physics Mode",            attr="PHYSICS_MODE",
         type="choice", choices=["realistic","2-body"]),
    dict(name="GR Curvature",            attr="GR_CURVATURE_EFFECT",     type="bool"),
    dict(name="Lense-Thirring Spin",     attr="BH_SPIN_LENSE_THIRRING",  type="bool"),
    dict(name="Object Gravity",          attr="OBJECT_GRAVITY",          type="bool"),
    dict(name="Orbit Energy Decay",      attr="ORBIT_ENERGY_DECAY",
         type="float", min=0.0, max=0.1, step=0.002,   unit="/s"),
    dict(name="Multi-Body Noise",        attr="MULTI_BODY_NOISE",
         type="float", min=0.0, max=0.02, step=0.001,  unit="σ"),
    dict(name="Particle Chaos",          attr="PARTICLE_DYNAMICS_NOISE",
         type="float", min=0.0, max=0.2, step=0.01,    unit="σ"),
    dict(name="Global Brightness",       attr="GLOBAL_BRIGHTNESS",
         type="float", min=0.1, max=4.0, step=0.1,     unit="×"),
    dict(name="Disk Brightness",         attr="DISK_BRIGHTNESS",
         type="float", min=0.1, max=5.0, step=0.1,     unit="×"),
    dict(name="Star Count",              attr="STAR_COUNT",
         type="int", min=0, max=15000, step=500,        unit="★"),
    dict(name="Disk Particle Count",     attr="DISK_PARTICLE_COUNT",
         type="int", min=0, max=150000, step=500,        unit="pts"),
    dict(name="Virtual Accretion Disk",  attr="USE_VIRTUAL_ACCRETION_DISK", type="bool"),
    dict(name="Realistic Stars (3D)",    attr="REALISTIC_STARS",            type="bool"),
    dict(name="Redshift Fading",         attr="ENABLE_REDSHIFT_FADING",     type="bool"),
    dict(name="Particle Temp Glow",      attr="PARTICLE_TEMP_GLOW",         type="bool"),
    dict(name="Spaghettification",       attr="PLANET_SPAGHETTIFICATION",   type="bool"),
    dict(name="Roche Limit Base",        attr="ROCHE_LIMIT_BASE",
         type="float", min=1.0, max=60.0, step=1.0,    unit="R_s"),
    dict(name="Planet Cohesion",         attr="PLANET_COHESION",
         type="float", min=0.05, max=5.0, step=0.05,   unit="×"),
    dict(name="Gas Emission Rate",       attr="GAS_EMISSION_RATE",
         type="float", min=0.1, max=10.0, step=0.1,    unit="×"),
    dict(name="Plunge Factor",           attr="PARTICLE_PLUNGE_FACTOR",
         type="float", min=0.0, max=2.0, step=0.1,     unit="×"),
    dict(name="Particle Force",          attr="PARTICLE_FORCE",             type="bool"),
    dict(name="Particle Force Strength", attr="PARTICLE_FORCE_STRENGTH",
         type="float", min=0.0, max=0.01, step=0.0001, unit="G_eff"),
    dict(name="Particle Auto-Zoom",      attr="PARTICLE_AUTO_ZOOM",         type="bool"),
    dict(name="Particle Base Size",      attr="PARTICLE_BASE_SIZE",
         type="float", min=0.1, max=5.0, step=0.1,     unit="px"),
    dict(name="Real Light Bend (Donut)", attr="REAL_LIGHT_BEND",            type="bool"),
    dict(name="Render Distance (0=Inf)", attr="RENDER_DISTANCE",
         type="float", min=0.0, max=50.0, step=1.0,    unit="R_s"),
    dict(name="Random Particle Size",    attr="RANDOM_PARTICLE_SIZE",       type="bool"),
    dict(name="Min Random Size",         attr="MIN_SIZE_RANDOM",
         type="float", min=0.1, max=3.0, step=0.1,     unit="px"),
    dict(name="Max Random Size",         attr="MAX_SIZE_RANDOM",
         type="float", min=1.0, max=8.0, step=0.1,     unit="px"),
    dict(name="Brightness By Velocity",  attr="BRIGHTNESS_BY_VELOCITY",     type="bool"),
    dict(name="Particle Absorber",       attr="PARTICLE_ABSORBER",          type="bool"),
    dict(name="Show Physical Units",     attr="SHOW_UNIT",                  type="bool"),
]